import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";

export async function POST(request: NextRequest) {
  try {
    const { gameCode, prompt, gameTitle } = await request.json();
    
    console.log("[SaveProject] Saving game to example-project:", gameTitle);
    
    // Clear existing example-project
    const projectPath = path.join(process.cwd(), "example-project");
    if (fs.existsSync(projectPath)) {
      fs.rmSync(projectPath, { recursive: true, force: true });
    }
    fs.mkdirSync(projectPath, { recursive: true });
    
    // Parse and organize the game code
    const parsedFiles = parseGameCode(gameCode, gameTitle);
    
    // Write parsed files to example-project
    for (const file of parsedFiles) {
      const filePath = path.join(projectPath, file.filename);
      const dir = path.dirname(filePath);
      
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      
      fs.writeFileSync(filePath, file.content, 'utf-8');
    }
    
    // Store metadata about the import
    const metadata = {
      originalPrompt: prompt,
      gameTitle: gameTitle,
      importedAt: new Date().toISOString(),
      sourceSystem: "Level0-KimiK2",
      filesCreated: parsedFiles.map(f => f.filename)
    };
    
    fs.writeFileSync(
      path.join(projectPath, "import_metadata.json"), 
      JSON.stringify(metadata, null, 2)
    );
    
    console.log(`[SaveProject] Created ${parsedFiles.length} files from Level0 game`);
    
    return NextResponse.json({
      success: true,
      filesCreated: parsedFiles.length,
      projectPath: "example-project",
      metadata: metadata
    });
    
  } catch (error) {
    console.error("[SaveProject] Error saving game:", error);
    return NextResponse.json(
      { error: "Failed to save game to project" },
      { status: 500 }
    );
  }
}

function parseGameCode(gameCode: string, gameTitle: string): Array<{filename: string, content: string}> {
  const files: Array<{filename: string, content: string}> = [];
  
  try {
    // Extract the scene class
    const sceneMatch = gameCode.match(/class\s+(\w*Scene\w*)[^{]*\{[^]*?\n\}/);
    
    if (sceneMatch) {
      const sceneName = sceneMatch[1];
      const sceneCode = sceneMatch[0];
      
      // Create scene file
      files.push({
        filename: `scenes/${sceneName}.js`,
        content: `// ${sceneName} - ${gameTitle}\n// Generated by Level0 + KimiK2\n\n${sceneCode}`
      });
      
      // Create main.js with game configuration
      const mainContent = `// ${gameTitle} - Game Configuration
// Generated by Level0 + KimiK2

// Import scene (in a real project, you'd use proper imports)
// For now, the scene is loaded separately

// Game Configuration
class Game {
    constructor() {
        this.config = {
            type: Phaser.AUTO,
            width: 800,
            height: 600,
            parent: 'game-container',
            backgroundColor: '#2c3e50',
            physics: {
                default: 'arcade',
                arcade: {
                    gravity: { y: 0 },
                    debug: false
                }
            },
            scene: [${sceneName}]
        };
        
        this.game = new Phaser.Game(this.config);
    }
}

// Start the game when page loads
window.addEventListener('load', () => {
    new Game();
});`;

      files.push({
        filename: "main.js",
        content: mainContent
      });
    } else {
      // Fallback: create single main.js with all code
      files.push({
        filename: "main.js",
        content: `// ${gameTitle} - Generated by Level0 + KimiK2\n\n${gameCode}`
      });
    }
    
    // Create index.html
    const scriptTags = files
      .filter(f => f.filename.endsWith('.js'))
      .map(f => `    <script src="${f.filename}"></script>`)
      .join('\n');
      
    const indexContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${gameTitle}</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background: #1a1a1a;
            font-family: Arial, sans-serif;
        }
        #game-container {
            border: 2px solid #333;
            border-radius: 8px;
        }
        canvas {
            display: block;
        }
    </style>
</head>
<body>
    <div id="game-container"></div>
    
    <!-- Phaser.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/phaser/3.70.0/phaser.min.js"></script>
    
    <!-- Game Files -->
${scriptTags}
</body>
</html>`;

    files.push({
      filename: "index.html",
      content: indexContent
    });
    
  } catch (error) {
    console.error("[SaveProject] Error parsing game code:", error);
    // Fallback: create basic structure
    files.push({
      filename: "main.js", 
      content: `// ${gameTitle} - Generated by Level0 + KimiK2\n\n${gameCode}`
    });
    
    files.push({
      filename: "index.html",
      content: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${gameTitle}</title>
    <style>
        body { margin: 0; padding: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; background: #1a1a1a; }
        #game-container { border: 2px solid #333; border-radius: 8px; }
        canvas { display: block; }
    </style>
</head>
<body>
    <div id="game-container"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/phaser/3.70.0/phaser.min.js"></script>
    <script src="main.js"></script>
</body>
</html>`
    });
  }
  
  return files;
}
