import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";

export async function POST(request: NextRequest) {
  try {
    const { gameCode, prompt, gameTitle } = await request.json();
    
    console.log("[Integration] Receiving game from Level0:", gameTitle);
    
    // Clear existing example-project
    const projectPath = path.join(process.cwd(), "example-project");
    if (fs.existsSync(projectPath)) {
      fs.rmSync(projectPath, { recursive: true, force: true });
    }
    fs.mkdirSync(projectPath, { recursive: true });
    
    // Parse the single HTML file from Claude Opus
    const parsedFiles = parseClaudeOpusCode(gameCode, gameTitle);
    
    // Write parsed files to example-project
    for (const file of parsedFiles) {
      const filePath = path.join(projectPath, file.filename);
      const dir = path.dirname(filePath);
      
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
      
      fs.writeFileSync(filePath, file.content, 'utf-8');
    }
    
    // Store metadata about the import
    const metadata = {
      originalPrompt: prompt,
      gameTitle: gameTitle,
      importedAt: new Date().toISOString(),
      sourceSystem: "Level0-ClaudeOpus",
      filesCreated: parsedFiles.map(f => f.filename)
    };
    
    fs.writeFileSync(
      path.join(projectPath, "import_metadata.json"), 
      JSON.stringify(metadata, null, 2)
    );
    
    console.log(`[Integration] Created ${parsedFiles.length} files from Level0 game`);
    
    return NextResponse.json({
      success: true,
      filesCreated: parsedFiles.length,
      projectPath: "example-project",
      metadata: metadata
    });
    
  } catch (error) {
    console.error("[Integration] Error importing Level0 game:", error);
    return NextResponse.json(
      { error: "Failed to import game from Level0" },
      { status: 500 }
    );
  }
}

function parseClaudeOpusCode(htmlCode: string, gameTitle: string): Array<{filename: string, content: string}> {
  const files: Array<{filename: string, content: string}> = [];
  
  try {
    // Extract script content from HTML
    const scriptRegex = /<script(?:\s+[^>]*)?>([^]*?)<\/script>/gi;
    const scripts: string[] = [];
    let match;
    
    while ((match = scriptRegex.exec(htmlCode)) !== null) {
      const scriptContent = match[1].trim();
      if (scriptContent && !scriptContent.includes('phaser.min.js') && !scriptContent.includes('cdnjs')) {
        scripts.push(scriptContent);
      }
    }
    
    // If we have script content, split it intelligently
    if (scripts.length > 0) {
      const allCode = scripts.join('\n\n');
      const parsedFiles = splitGameCode(allCode, gameTitle);
      files.push(...parsedFiles);
    }
    
    // Create index.html
    const cleanHtml = createCleanIndexHtml(gameTitle, files);
    files.push({
      filename: "index.html",
      content: cleanHtml
    });
    
    // If no files were parsed, create a basic structure
    if (files.length === 1) { // Only index.html
      files.push({
        filename: "main.js",
        content: `// ${gameTitle} - Generated by Level0 + Claude Opus\n\n${scripts.join('\n\n')}`
      });
    }
    
  } catch (error) {
    console.error("[Integration] Error parsing code:", error);
    // Fallback: create single main.js with all code
    files.push({
      filename: "main.js", 
      content: `// ${gameTitle} - Generated by Level0 + Claude Opus\n\n// Original HTML:\n/*\n${htmlCode}\n*/`
    });
    
    files.push({
      filename: "index.html",
      content: createCleanIndexHtml(gameTitle, [{filename: "main.js", content: ""}])
    });
  }
  
  return files;
}

function splitGameCode(code: string, gameTitle: string): Array<{filename: string, content: string}> {
  const files: Array<{filename: string, content: string}> = [];
  
  // Look for class definitions
  const classRegex = /class\s+(\w+)[^{]*\{[^}]*\}/gs;
  const classes = [...code.matchAll(classRegex)];
  
  // Look for scene definitions
  const sceneClasses = classes.filter(match => 
    match[1].toLowerCase().includes('scene') || 
    match[0].includes('extends Phaser.Scene')
  );
  
  // Look for sprite/entity classes
  const spriteClasses = classes.filter(match => 
    !match[1].toLowerCase().includes('scene') &&
    (match[1].toLowerCase().includes('player') ||
     match[1].toLowerCase().includes('enemy') ||
     match[1].toLowerCase().includes('bullet') ||
     match[0].includes('extends Phaser.'))
  );
  
  // Create scene files
  sceneClasses.forEach(sceneMatch => {
    files.push({
      filename: `scenes/${sceneMatch[1]}.js`,
      content: `// ${sceneMatch[1]} - ${gameTitle}\n\n${sceneMatch[0]}`
    });
  });
  
  // Create sprite files
  spriteClasses.forEach(spriteMatch => {
    files.push({
      filename: `sprites/${spriteMatch[1]}.js`, 
      content: `// ${spriteMatch[1]} - ${gameTitle}\n\n${spriteMatch[0]}`
    });
  });
  
  // Create main.js with remaining code
  let mainCode = code;
  [...sceneClasses, ...spriteClasses].forEach(match => {
    mainCode = mainCode.replace(match[0], '');
  });
  
  files.push({
    filename: "main.js",
    content: `// ${gameTitle} - Game Configuration\n\n${mainCode.trim()}`
  });
  
  return files;
}

function createCleanIndexHtml(gameTitle: string, files: Array<{filename: string}>) {
  const scriptTags = files
    .filter(f => f.filename.endsWith('.js'))
    .map(f => `    <script src="${f.filename}"></script>`)
    .join('\n');
    
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${gameTitle}</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background: #1a1a1a;
            font-family: Arial, sans-serif;
        }
        #game-container {
            border: 2px solid #333;
            border-radius: 8px;
        }
        canvas {
            display: block;
        }
    </style>
</head>
<body>
    <div id="game-container"></div>
    
    <!-- Phaser.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/phaser/3.70.0/phaser.min.js"></script>
    
    <!-- Game Files -->
${scriptTags}
</body>
</html>`;
}
